
OPENAI_API_KEY = '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'
WOLFRAM_ALPHA_APPID ='3PKQ94-XQ8J8EYXQV'
GOOGLE_API_KEY ='AIzaSyDnazOYWZd-8yafnCH4LwAJ-10z3xVcd2k'
PINECONEKEY = '19e1c16f-3d84-433b-b9dc-292aedb1aee9'
PINECONENV ='asia-southeast1-gcp-free'
GOOGLE_CSE_ID ='56b5165f44e3a4d6d'
DETA_USER_AUTH = 'b0yngmegabr_WPiBpBVdtbCmXyzUnJhHnQyh24ydQuie'
ZAPIER_NLA_API_KEY = 'sk-ak-Qa7AZr7Emg4lEzijsX5xJuPNgM'
ZAPIER_CLIENT_ID = 'nla-1aVAfeRgOZMKmXhNCcsZXqEo8xj4L53y5DR1'
ZAPIER_CLIENT_SECRET = '4d709a6b7d0e0735d3c86b3c378b0d4f037a070da0eed66d17b7246be70bffcb'